/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroSection from "./Components/HeroSection";
import StorySection from "./Components/StorySection";
import OurStorySection from "./Components/OurStorySection";
import ChefSection from "./Components/ChefSection";
import Header from "../../components/header/Header";
import SpecialServices from "./Components/SpecialService/SpecialServices";
import TeamSection from "./Components/TeamSection/TeamSection";
import Footer from "../../components/footer/Footer";

const services = [
    {
        title: "Birthday Party",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    },
    {
        title: "Wedding Party",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    },
];

const AboutUs: React.FC = () => {
    return (
        <main className="flex flex-col items-center">
            <Header />
            <HeroSection />
            <StorySection />
            <OurStorySection />
            <ChefSection />
            <SpecialServices services={services} />
            <TeamSection />
            <Footer />
        </main>
    );
};

export default AboutUs;
