/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FormSection from "./FormSection";
import OrderItem from "./OrderItem";
interface OrdersFormProps {}

const listOrders = [
    {
        order_id: 1,
        delivery_time: "10:00 AM",
        status: "Delivered",
        total: 1000,
        orderItems: [
            {
                id: 1,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 1",
                quantity: 2,
                price: 111,
            },
            {
                id: 2,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 2",
                quantity: 1,
                price: 111,
            },
        ],
    },
    {
        order_id: 2,
        delivery_time: "10:00 AM",
        status: "Delivered",
        total: 1000,
        orderItems: [
            {
                id: 1,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 1",
                quantity: 2,
                price: 111,
            },
            {
                id: 2,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 2",
                quantity: 1,
                price: 111,
            },
        ],
    },
    {
        order_id: 3,
        delivery_time: "10:00 AM",
        status: "Delivered",
        total: 1000,
        orderItems: [
            {
                id: 1,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 1",
                quantity: 2,
                price: 111,
            },
            {
                id: 2,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 2",
                quantity: 1,
                price: 111,
            },
        ],
    },
    {
        order_id: 4,
        delivery_time: "10:00 AM",
        status: "Delivered",
        total: 1000,
        orderItems: [
            {
                id: 1,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 1",
                quantity: 2,
                price: 111,
                total: 100,
            },
            {
                id: 2,
                image: "https://res.cloudinary.com/dytan1asl/image/upload/v1729066425/fAndb/qxqdiseb4fvpwcevxorp.png",
                title: "Product 2",
                quantity: 1,
                price: 111,
                total: 50,
            },
        ],
    },
];

const OrdersForm: React.FC<OrdersFormProps> = ({}) => {
    return (
        <div className="flex flex-col sm:w-[60%] max-sm:w-full max-md:mt-10 pr-[30px]">
            <FormSection title="Orders">
                <div className="flex flex-col gap-5 pt-5">
                    {listOrders.map((order, index) => (
                        <OrderItem key={index} items={order} />
                    ))}
                </div>
            </FormSection>
        </div>
    );
};

export default OrdersForm;
