/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";

interface ProfileSidebarProps {
  name: string;
  title: string;
  imageUrl: string;
}

const ProfileSidebar: React.FC<ProfileSidebarProps> = ({
  name,
  title,
  imageUrl,
}) => {
  const sidebarItems = [
    { label: "Profile", isActive: true },
    { label: "My Cart", isActive: false },
    { label: "Wishlist", isActive: false },
    { label: "Shop", isActive: false },
    { label: "Help Desk", isActive: false },
    { label: "Logout", isActive: false },
  ];

  return (
    <aside className="flex flex-col w-[30%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col max-md:mt-10">
        <div className="flex flex-col items-center px-16 pt-8 pb-24 bg-orange-50 max-md:px-5">
          <div className="flex flex-col max-w-full w-[132px]">
            <img
              loading="lazy"
              src={imageUrl}
              alt={`Profile picture of ${name}`}
              className="object-contain w-full rounded-full aspect-square max-md:mr-1.5"
            />
            <h2 className="mt-2.5 text-2xl text-slate-700">{name}</h2>
            <p className="mt-1 text-lg text-red-600 max-md:mr-2">{title}</p>
          </div>
        </div>
        <nav>
          {sidebarItems.map((item, index) => (
            <SidebarItem
              key={index}
              label={item.label}
              isActive={item.isActive}
            />
          ))}
        </nav>
      </div>
    </aside>
  );
};

export default ProfileSidebar;
