/**
 * This code was generated by Builder.io.
 */
import React from "react";

import Header from "../../components/header/Header";

import Footer from "../../components/footer/Footer";
import HeroSection from "./components/HeroSection";
import ShoppingCart from "./components/ShoppingCart/ShoppingCart";

const AboutUs: React.FC = () => {
    return (
        <main className="flex flex-col items-center">
            <Header />
            <HeroSection />
            <ShoppingCart />
            <Footer />
        </main>
    );
};

export default AboutUs;
