/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/Footer";
import ContactSection from "./Components/ContactSection";
import HeroSection from "./Components/HeroSection";

const Contact: React.FC = () => {
    return (
        <main className="flex flex-col items-center">
            <Header />
            <HeroSection />
            <ContactSection />
            <Footer />
        </main>
    );
};

export default Contact;
