/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductList from "../ProductList/ProductList";
import ShippingCalculator from "../ShippingCalculator/ShippingCalculator";
import CartSummary from "../CartSummary/CartSummary";

const ShoppingCart: React.FC = () => {
    return (
        <main className="flex flex-col">
            <ProductList/>
            <div className="mt-12 w-full max-md:mt-10 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                    <div className="flex flex-col items-center justify-center w-6/12 max-md:ml-0 max-md:w-full max-sm:pl-0 sm:pl-16">
                        <ShippingCalculator />
                    </div>
                    <div className="flex flex-col items-center justify-center w-6/12 max-md:ml-0 max-md:w-full  max-sm:pr-0 sm:pr-16">
                        <CartSummary
                            shipping="Free Shipping"                 
                        />
                    </div>
                </div>
            </div>
        </main>
    );
};

export default ShoppingCart;
