/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ShippingCalculator: React.FC = () => {
  return (
    <section className="flex flex-col grow px-20 pt-3.5 pb-11 mt-1.5 w-full text-lg text-red-600 bg-orange-50 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-stretch text-4xl font-bold">CALCULATE SHIPPING</h2>
      <form className="flex flex-col items-start">
        <div className="flex gap-4 px-3.5 py-4 mt-12 text-white bg-red-600 rounded-xl border-2 border-red-600 border-solid max-md:mt-10">
          <label htmlFor="paymentGateway" className="grow">
            Select Your payment gateway
          </label>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2e9e18a4519bdeb5d3af0dd491c501febbe37a09c40c3ceaa95d42bb0cdbc98b?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
            alt=""
            className="object-contain shrink-0 my-auto w-5 aspect-[1.67] fill-white"
          />
        </div>
        <select id="paymentGateway" className="sr-only">
          <option value="">Select payment gateway</option>
        </select>
        <div className="flex gap-5 justify-between px-3.5 py-4 mt-5 max-w-full bg-white rounded-xl border-2 border-red-600 border-solid w-[300px]">
          <input
            type="text"
            id="cardNumber"
            placeholder="Card number"
            aria-label="Card number"
          />
          <input
            type="text"
            id="cvcDate"
            placeholder="CVC/Date"
            aria-label="CVC/Date"
          />
        </div>
        <input
          type="text"
          id="couponCode"
          placeholder="Coupon Code(if you have)"
          aria-label="Coupon Code"
          className="px-3.5 py-4 mt-5 max-w-full bg-white rounded-xl border-2 border-red-600 border-solid w-[300px] max-md:pr-5"
        />
        <button
          type="submit"
          className="self-center px-7 py-4 mt-14 ml-4 w-52 max-w-full text-2xl text-white bg-red-600 rounded-xl max-md:px-5 max-md:mt-10"
        >
          Apply Coupon
        </button>
      </form>
    </section>
  );
};

export default ShippingCalculator;
