/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InputField from "./InputField";
import Button from "./Button";
import CheckboxField from "./CheckboxField";

interface LoginRegisterProps {
  // Add any props if needed
}

const LoginRegister: React.FC<LoginRegisterProps> = () => {
  return (
    <main className="flex gap-5 max-md:flex-col">
      <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col items-start pt-5 pr-20 pb-10 mx-auto w-full text-2xl text-red-600 bg-orange-50 max-md:mt-10 max-md:max-w-full">
          <h2 className="text-4xl font-bold">Login</h2>
          <form>
            <InputField label="Username or email address" required />
            <InputField label="Password" type="password" required />
            <Button>Log in</Button>
            <CheckboxField label="Remember me" />
          </form>
          <a href="#" className="mt-4 text-green-400">
            Lost your password?
          </a>
        </div>
      </section>
      <section className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col grow items-start pt-5 pr-5 pb-48 pl-14 w-full text-lg text-red-600 bg-orange-50 max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:max-w-full">
          <h2 className="text-4xl font-bold">Register</h2>
          <form>
            <InputField label="Email address" type="email" required />
            <p className="self-stretch mt-4 max-md:max-w-full">
              A link to set a new password will be sent to your email address.
            </p>
            <Button>Register</Button>
          </form>
        </div>
      </section>
    </main>
  );
};

export default LoginRegister;
